[package]
name = "rust-advanced-encryption-standard"
version = "0.1.0"
edition = "2021"

[dependencies]
cipher = "0.4.4"
clap = { version = "4.5.41", features = ["derive"] }
getrandom = "0.3.3"
hex = "0.4.3"
